### ISSUE TITLE
Change the post title value

### ISSUE THREAD

**Issue by hydrostaticcog** [tazz4843/nbb#2]
Currently post titles are the name of the file that they are stored in. This causes some ugly post titles if they are more than one word.

Perhaps you could just make the post title the first markdown header?

**Comment by tazz4843** [comment]
Making it the first markdown title introduces incredible complexity, since right now it's essentially "render and serve", where we never see the actual syntax of the markdown document. This would need to pretty much be torn up and redone, with a bit of parsing the AST from nbb code. I personally think the current filename technique is good enough, ugly filenames on the server side are really a non-issue.

**Comment by hydrostaticcog** [comment]
I was referring to the front side post name, not server side.

**Comment by tazz4843** [comment]
As in the client-side rendered name? It shouldn't be stripping spaces in the name.

**Comment by hydrostaticcog** [comment]
The client-side rendered name includes those dashes like the file name. You can't include the spaces in the file name since it will break http.

**Comment by tazz4843** [comment]
Oh, I see what you mean. Fix should be relatively simple, just percent encode the URL. I'm not sure I'll remember to do that tbh lol
